# Translations template for COVID-19 Bot.
# Copyright (C) 2020 ORGANIZATION
# This file is distributed under the same license as the COVID-19 Bot
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: COVID-19 Bot v5.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2020-12-17 11:46-0700\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.8.0\n"

#: ../cogs/autoupdater.py:53
msgid ""
"‚ùå Did you really try to set the autoupdater delay to more than a year? "
"Oi. Anyways, that isn't allowed. Try again with a more reasonable delay."
msgstr ""

#: ../cogs/autoupdater.py:62
msgid ""
"‚ùå You already have a autoupdater set in this channel! Remove it with "
"`/disable_updates` and try again!"
msgstr ""

#: ../cogs/autoupdater.py:70
msgid ""
"‚ö† You're setting a delay longer than 1 day! Are you sure you want to do "
"this? To confirm, type `ok` within 15 seconds."
msgstr ""

#: ../cogs/autoupdater.py:75
msgid "Action cancelled. Set up a new autoupdater with `/autoupdate <delay>`."
msgstr ""

#: ../cogs/autoupdater.py:78
msgid "Continuing setup..."
msgstr ""

#: ../cogs/autoupdater.py:83
msgid ""
"You're setting the autoupdater to less than 10 minutes delay. I'll skip "
"the check because you are a premium guild/user. <3 from 0/0#0001"
msgstr ""

#: ../cogs/autoupdater.py:86
msgid ""
"‚ùå You can't set the autoupdater delay to less than 10 minutes unless you "
"are a premium guild.\n"
"Hint: there's no point in setting it to less than 10 minutes due to the "
"fact the stats updater only fires once every 10 minutes. If you really "
"want to get a shorter delay (no point in doing so), check out the "
"`/donate` command."
msgstr ""

#: ../cogs/autoupdater.py:95
msgid ""
"‚ùå Failed to get a ISO2 code for the country! `/list` will show you a list"
" of countries and their IDs."
msgstr ""

#: ../cogs/autoupdater.py:117
msgid "‚úÖ Posting stats for {0} in this channel every {1}."
msgstr ""

#: ../cogs/autoupdater.py:128
msgid "‚úÖ Disabled autoupdates in this channel."
msgstr ""

#: ../cogs/autoupdater.py:130 ../cogs/autoupdater.py:139
msgid "‚ùå You don't have a autoupdater set here!"
msgstr ""

#: ../cogs/autoupdater.py:144
msgid "‚úÖ Forcing a update sometime in the next minute."
msgstr ""

#: ../cogs/autoupdater.py:158
msgid "‚úÖ Next update: {htd}"
msgstr ""

#: ../cogs/autoupdater.py:229
msgid ""
"I'm having a issue with finding the country name here! Here's what I'm "
"showing: {trying}"
msgstr ""

#: ../cogs/background_updates.py:23
msgid "Stopping task..."
msgstr ""

#: ../cogs/background_updates.py:25
msgid "Task has been sent a stop signal. Waiting 10 seconds..."
msgstr ""

#: ../cogs/background_updates.py:27
msgid "Sending terminate signal..."
msgstr ""

#: ../cogs/background_updates.py:29
msgid "Task has been killed. Starting now..."
msgstr ""

#: ../cogs/background_updates.py:31
msgid "Task has been sent a start signal."
msgstr ""

#: ../cogs/background_updates.py:33
msgid "Task restarted!"
msgstr ""

#: ../cogs/covid.py:63
msgid ""
"A fatal error has happened! The world data seems to have gone missing. "
"Please let a mod in the bot's support server know."
msgstr ""

#: ../cogs/covid.py:76
msgid "Didn't find any continents with that name!"
msgstr ""

#: ../cogs/covid.py:91
msgid "Use the `{prefix}covid world` command instead."
msgstr ""

#: ../cogs/covid.py:95
msgid ""
"Didn't find a country with that name, or the country has no cases! Try "
"searching for the name with `{prefix}list country`.\n"
"Hint: if you're looking for North or South Korea, try `{prefix}covid KP` "
"or `{prefix}covid KR` for North and South Korea, respectively!"
msgstr ""

#: ../cogs/covid.py:101
msgid ""
"Didn't find a country with that name, or the country has no cases! Try "
"searching for the name with `{prefix}list country`."
msgstr ""

#: ../cogs/covid.py:105
msgid "You've used a incorrect command: try `{ctx.prefix}covid {country_test[0]}`"
msgstr ""

#: ../cogs/database_commands.py:40
msgid "The server prefix is set to `{prefix}`."
msgstr ""

#: ../cogs/database_commands.py:43
msgid "There is no specific prefix set for this guild."
msgstr ""

#: ../cogs/database_commands.py:61
msgid "The server language is now set to `{language}`."
msgstr ""

#: ../cogs/database_commands.py:68
msgid "There is no specific language set for this guild."
msgstr ""

#: ../cogs/database_commands.py:76
msgid "Tips are currently enabled for this guild."
msgstr ""

#: ../cogs/database_commands.py:78
msgid "Tips are currently disabled for this guild."
msgstr ""

#: ../cogs/database_commands.py:83
msgid "Enabled tips for this guild."
msgstr ""

#: ../cogs/database_commands.py:85
msgid "Disabled tips for this guild."
msgstr ""

#: ../cogs/database_commands.py:99
msgid ""
"The API has been disabled for this channel. To restore your permissions, "
"contact 0/0#0001 on the official support server."
msgstr ""

#: ../cogs/database_commands.py:104
msgid "DMed your API key to you."
msgstr ""

#: ../cogs/database_commands.py:107
msgid "Revoked/deleted API key."
msgstr ""

#: ../cogs/database_commands.py:115
msgid "DMed your new API key to you."
msgstr ""

#: ../cogs/database_commands.py:125
msgid "Disabled the API for {name}."
msgstr ""

#: ../cogs/error_handling.py:68
msgid ""
"There was an error converting one of your arguments with "
"{exception.converter}. The correct syntax would be "
"`{command_invoke_help}`. The converter returned the following error: "
"{original}"
msgstr ""

#: ../cogs/error_handling.py:71
msgid ""
"This command is missing an argument. The correct syntax would be "
"`{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:75
msgid ""
"Too many quotes were provided in your message: don't forget to escape "
"your quotes like this `\\{exception.quote}`. The correct syntax for the "
"command is `{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:81
msgid ""
"A space was expected after a closing quote, but I found {exception.char}."
" Please check that you are using the correct syntax: "
"`{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:86
msgid ""
"A closing quote was expected, but wasn't found. Don't forget to close "
"your quotes with `{exception.close_quote}` at the end of your argument. "
"Please check that you are using the correct syntax: "
"`{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:92
msgid ""
"Too many arguments were passed in this command. Please check that you are"
" using the correct syntax: `{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:96
msgid ""
"The way you are invoking this command is confusing me. The correct syntax"
" would be `{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:101
msgid ""
"An argument passed was incorrect. `{exception}`.Please check that you are"
" using the correct syntax: `{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:108
msgid ""
"{exception} Please check that you are using the correct syntax: "
"`{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:116
msgid "This command can only be used in a private message."
msgstr ""

#: ../cogs/error_handling.py:118
msgid "This command cannot be used in a private message."
msgstr ""

#: ../cogs/error_handling.py:120
msgid ""
"Multiple errors were encountered when running your command: "
"{exception.errors}"
msgstr ""

#: ../cogs/error_handling.py:123
msgid "You need to be the owner of the bot to run that."
msgstr ""

#: ../cogs/error_handling.py:139
msgid "You need to be in a NSFW channel to run that."
msgstr ""

#: ../cogs/error_handling.py:145
msgid ""
"You need to be in the {correct_guild.name} server "
"(`{exception.must_be_in_guild_id}`)."
msgstr ""

#: ../cogs/error_handling.py:150
msgid "You need to be in a server with ID {exception.must_be_in_guild_id}."
msgstr ""

#: ../cogs/error_handling.py:153
msgid "You have the `{exception.permission}` permission."
msgstr ""

#: ../cogs/error_handling.py:156
msgid "You need the `{exception.permission}` permission."
msgstr ""

#: ../cogs/error_handling.py:159
msgid ""
"You have {exception.required} or more of the following permissions: "
"`{exception.permissions}`."
msgstr ""

#: ../cogs/error_handling.py:163
msgid ""
"You need {exception.required} or more of the following permissions: "
"`{exception.permissions}`."
msgstr ""

#: ../cogs/error_handling.py:174
msgid "The provided command was not found."
msgstr ""

#: ../cogs/error_handling.py:176
msgid "That command has been disabled."
msgstr ""

#: ../cogs/error_handling.py:179
msgid ""
"I don't have permissions to send messages there! Try again somewhere I do"
" have permissions to send messages!"
msgstr ""

#: ../cogs/error_handling.py:182
msgid ""
"There was an error running the specified command. This error has been "
"logged."
msgstr ""

#: ../cogs/error_handling.py:197
msgid "You are being ratelimited. Please try again {some_time}."
msgstr ""

#: ../cogs/error_handling.py:201
msgid ""
"Simulations have been disabled in this guild due to a missing permission."
" Ask a admin to give me the Manage Messages permission."
msgstr ""

#: ../cogs/error_handling.py:208
msgid ""
"This should not have happened. A command raised an error that does not "
"comes from CommandError. Please inform the owner."
msgstr ""

#: ../cogs/error_handling.py:213
msgid ""
"\n"
"For help, join the bot's support server at {invite}"
msgstr ""

#: ../cogs/future_simulations.py:102
msgid "Didn't get a response. To try again, do `{prefix}{qn}`."
msgstr ""

#: ../cogs/graphs.py:19
msgid "Couldn't find that name. Try again, or use `{prefix}list` for help."
msgstr ""

#: ../cogs/graphs.py:30
msgid ""
"React with üìà for a logarithmic graph.\n"
"React with üìâ for a linear graph.\n"
"This message expires after 30 seconds."
msgstr ""

#: ../cogs/graphs.py:44
msgid "Timed out. Request a new message with `{prefix}graphs`"
msgstr ""

#: ../cogs/graphs.py:47
msgid "Please wait, this could take a few seconds..."
msgstr ""

#: ../cogs/graphs.py:50
msgid "Graph for {location}"
msgstr ""

#: ../cogs/maps.py:41
msgid ""
"I don't know what map you're looking for! Run `{ctx.prefix}maps types` to"
" see all the maps I can show you!"
msgstr ""

#: ../cogs/permissions_commands.py:51
msgid "üòÉ You have that permission."
msgstr ""

#: ../cogs/permissions_commands.py:53
msgid "‚òπÔ∏è You don't have that permission."
msgstr ""

#: ../cogs/permissions_commands.py:56
msgid "Details of permissions hierarchy"
msgstr ""

#: ../cogs/permissions_commands.py:62
msgid "{sign} Default (from {sign}{by})"
msgstr ""

#: ../cogs/permissions_commands.py:77
msgid "{sign} Guild role {role} (from {sign}{by})"
msgstr ""

#: ../cogs/permissions_commands.py:88
msgid "{sign} Channel role {role} (from {sign}{by})"
msgstr ""

#: ../cogs/permissions_commands.py:95
msgid "{sign} Member (from {sign}{by})"
msgstr ""

#: ../cogs/permissions_commands.py:102
msgid "{sign} Fixed (from {sign}{by})"
msgstr ""

#: ../cogs/permissions_commands.py:109
msgid "{sign} User (from {sign}{by})"
msgstr ""

#: ../cogs/permissions_commands.py:132 ../cogs/permissions_commands.py:163
msgid "**{role} permissions**"
msgstr ""

#: ../cogs/permissions_commands.py:142
msgid "There are no specific permissions set in this guild."
msgstr ""

#: ../cogs/permissions_commands.py:173
msgid "There are no specific permissions set in this channel."
msgstr ""

#: ../cogs/permissions_commands.py:190
msgid "**{member.name}#{member.discriminator} permissions**"
msgstr ""

#: ../cogs/permissions_commands.py:198
msgid "There are no specific permissions for this member."
msgstr ""

#: ../cogs/permissions_commands.py:222
msgid ""
"üëå Permission {permission} for user {user.name}#{user.discriminator} has "
"been set to {value} globally."
msgstr ""

#: ../cogs/permissions_commands.py:239
msgid ""
"üëå Permission {permission} for member {member.name}#{member.discriminator}"
" has been set to {value} globally."
msgstr ""

#: ../cogs/permissions_commands.py:253
msgid "‚ùå Can't set permissions in a channel that is not in this guild."
msgstr ""

#: ../cogs/permissions_commands.py:257 ../cogs/permissions_commands.py:283
msgid "‚ùå Can't set permissions for a role that does not exist in this guild."
msgstr ""

#: ../cogs/permissions_commands.py:270
msgid ""
"üëå Permission {permission} for role {role_name} [`{role_id}`] has been set"
" to {value} in this channel."
msgstr ""

#: ../cogs/permissions_commands.py:296
msgid ""
"üëå Permission {permission} for role {role_name} [`{role_id}`] has been set"
" to {value} in this guild."
msgstr ""

#: ../cogs/utils.py:82
msgid "Pong. ‚Äî Time taken: {milliseconds}ms"
msgstr ""

#: ../utils/embeds.py:104
msgid "COVID-19 Stats for {name}"
msgstr ""

#: ../utils/embeds.py:107
msgid "Stats last updated at (UTC)"
msgstr ""

#: ../utils/embeds.py:120 ../utils/embeds.py:124
msgid "no data"
msgstr ""

#: ../utils/embeds.py:126
msgid "Affected Countries"
msgstr ""

#: ../utils/embeds.py:135
msgid "Country List"
msgstr ""

#: ../utils/embeds.py:136
msgid ""
"Use either the country name, or the ISO2/ISO3 code when getting stats "
"with `/covid <name>`!"
msgstr ""

